<?xml version="1.0" encoding="utf-8"?>

<wsdl:definitions 
    targetNamespace="http://www.ibm.com/wsdl4j/importA.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://ws-i.org/profiles/basic/1.1/wsdl11">
    
    <import namespace="http://www.ibm.com/wsdl4j/importB.wsdl" location="MyImportB.wsdl"></import>
    
    <wsdl:message name="HelloMessageC">
        <wsdl:part name="TestPartC" type="xsd:string"/>
    </wsdl:message>
</wsdl:definitions>
